const books = [
    {
        id: '1',
        title: 'Name of the Wind',
        series: 'The King Killer Chronicles',
        author: 'Patrick Rothfuss',
        genre : 'fantasy',
        url: 'https://www.goodreads.com/book/show/186074.The_Name_of_the_Wind?from_search=true&from_srp=true&qid=Vne38oZcxp&rank=1',
        published: '2007'
    },
    {
        id: '2',
        title: 'Red Rising',
        series: 'Red Rising Saga',
        author: 'Pierce Brown',
        genre: 'sci-fi',
        url: 'https://www.goodreads.com/book/show/15839976-red-rising?from_search=true&from_srp=true&qid=H72TskJAtb&rank=1',
        published: '2014',
    },
    {
        id: '3',
        title: 'The Way of Kings',
        series: 'The Stormlight Archive',
        author: 'Brandon Sanderson',
        genre: 'fantasy',
        url: 'https://www.goodreads.com/book/show/7235533-the-way-of-kings?from_search=true&from_srp=true&qid=I8oKKPcQgK&rank=1',
        published: '2010',
    },
    {
        id: '4',
        title: 'The Blade Itself',
        series: 'The First Law',
        author: 'Joe Abercrombie',
        genre: 'fantasy',
        url: 'https://www.goodreads.com/book/show/944073.The_Blade_Itself?from_search=true&from_srp=true&qid=5Xt40WzeNG&rank=1',
        published: '2007',
    },
    {
        id: '5',
        title: 'The Lies of Locke Lamora',
        series: 'The Gentlemen Bastards',
        author: 'Scott Lynch',
        genre: 'fantasy',
        url: 'https://www.goodreads.com/book/show/29588376-the-lies-of-locke-lamora',
        published: '2006',
    },
    {
        id: '6',
        title: 'The Shadow of the Gods',
        series: 'The Bloodsworn Saga',
        author: 'John Gwynne',
        genre: 'fantasy',
        url: 'https://www.goodreads.com/book/show/52694527-the-shadow-of-the-gods?from_search=true&from_srp=true&qid=yhjIq6mOuU&rank=1',
        published: '2021',
    },
    {
        id: '7',
        title: 'Leviathan Wakes',
        series: 'The Expanse',
        author: 'James S.A. Corey',
        genre: 'sci-fi',
        url: 'https://www.goodreads.com/book/show/8855321-leviathan-wakes?ac=1&from_search=true&qid=SRiyJKqH01&rank=1',
        published: '2011',
    },
    {
        id: '8',
        title: 'The Rage of Dragons',
        series: 'The Burning',
        author: 'Evan Winter',
        genre: 'fantasy',
        url: 'https://www.goodreads.com/book/show/41952489-the-rage-of-dragons?ac=1&from_search=true&qid=yhEq3yWbNy&rank=1',
        published: '2019',
    },
    {
        id: '9',
        title: 'Theft of Swords',
        series: 'The Riyria Revelations',
        author: 'Michael J. Sullivan',
        genre: 'fantasy',
        url: 'https://www.goodreads.com/book/show/10790290-theft-of-swords?ac=1&from_search=true&qid=4dzAXsD0ak&rank=1',
        published: '2011',
    },
];

module.exports = { books };